
title: <p align="center"> Abhishek Mishra </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/abhish-ek-mishra/">LinkedIn</a> |
  <a href="https://github.com/abhishek-vmishra">GitHub</a>
  
  <br>   
  I am a Freelance Computational Biologist.
  I have a Bachelors in Genetics/Biotechnolog, Masters in Biotechnology
  Currently persuing Masters in ML and AI
  Intrested in R & D, Worked with Companies like Yashraj Biotechnology, 
  CellKraft & Aerc India.
  <br>
  </p>



theme: jekyll-theme-minimal
